version: '3.3' 
services: 
  db: 
    environment: 
      MYSQL_DATABASE: dbIOTFC
      MYSQL_PASSWORD: errata
      MYSQL_ROOT_PASSWORD: Ogpdmllf2!
      MYSQL_USER: admin
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes: 
      - "~/Volumes/docker_db:/var/lib/mysql"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  management_server: 
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    ports: 
      - "8080:80"
    restart: always
    volumes: 
      - "~/Volumes/docker_phpmyadm:/var/www/phpmyadmin"
